export const genreData = {
  all: {
    genreNo: ["000", "001", "101", "007", "005", "003", "002", "006", "004"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合(全ジャンル)",
      "映画",
      "アニメ",
      "音楽",
      "漫画",
      "バイク",
      "ゲーム",
      "PCソフト・周辺機器",
    ],
    naviTitleEn: [
      "all",
      "movie",
      "animation",
      "music",
      "cartoon",
      "bike",
      "game",
      "pc-soft-accessory",
    ],
  },
  movie: {
    genreNo: ["001", "0011", "0012", "0013", "0014", "0015"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（映画）",
      "SFX",
      "アクション",
      "サスペンス",
      "ドラマ",
      "ホラー",
      "ドキュメンタリー",
      "歴史",
      "音楽",
    ],
    naviTitleEn: [
      "all-movie",
      "sfx",
      "action",
      "suspense",
      "drama",
      "horror",
      "documentary",
      "history",
      "music",
    ],
  },
  comic: {
    genreNo: ["007", "0071", "0072", "0073", "0074"],
    period: "daily",
    displayNumber: 5,
    naviTitle: ["総合（マンガ）", "少年マンガ", "少女マンガ", "アダルト", "BL"],
    naviTitleEn: [
      "all-cartoon",
      "for-boys",
      "for-girls",
      "for-adults",
      "boys-love",
    ],
  },
  music: {
    genreNo: ["005", "0051", "0052", "0053", "0054"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（洋書）",
      "J-Pop",
      "韓流",
      "洋楽",
      "EDM",
      "Hip Hop",
      "R&B",
      "Dance",
      "アイドル",
      "歌謡曲・演歌",
    ],
    naviTitleEn: [
      "all-music",
      "jpop",
      "kpop",
      "europeAndAmerica",
      "edm",
      "hiphop",
      "R&B",
      "dance",
      "idol",
      "kayoukyoku",
    ],
  },
  book: {
    genreNo: ["003", "0031", "0032", "0033", "0034"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（本）",
      "小説",
      "ジャーナリズム",
      "エッセイ",
      "絵本",
      "ビジネス",
      "自己啓発",
      "マネー",
    ],
    naviTitleEn: [
      "all-book",
      "novel",
      "journalism",
      "essay",
      "picture-book",
      "business",
      "self-development",
      "money",
    ],
  },
  motorcycle: {
    genreNo: ["002", "0021", "0022", "0023", "0024"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（バイク）",
      "中型ロード",
      "小型ロード",
      "大型ロード",
      "スクーター",
      "オフロード",
    ],
    naviTitleEn: [
      "all-bike",
      "medium-road-type",
      "small-road-type",
      "large-road-type",
      "scooter",
      "off-road",
    ],
  },
  game: {
    genreNo: ["006", "0061", "0062", "0063", "0064"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（ゲーム）",
      "ニンテンドースイッチ",
      "ニンテンドー3DS",
      "PS4",
      "おもちゃ",
    ],
    naviTitleEn: ["all-game", "nintendo-switch", "nintendo-3DS", "PS4", "toys"],
  },
  PC: {
    genreNo: ["004", "0041", "0042", "0043", "0044"],
    period: "daily",
    displayNumber: 5,
    naviTitle: [
      "総合（PC・周辺機器）",
      "タブレット・ノート",
      "PC",
      "ソフト",
      "周辺機器",
    ],
    naviTitleEn: ["all-pc", "tablet-note", "pc", "soft", "accessory"],
  },
};
